### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by dmitrydrynov** [techartorg/MXSPyCOM#10] opened 2019-09-20 10:50 UTC
I have this error on executing
MXSPyCOM -f C:\Projects\test\hello_world.ms

> Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'type')
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
>    at MXSPyCOM.Program.execute_max_commands(String[] args, String filepath)
>    at MXSPyCOM.Program.Main(String[] args)

Help, please!

**Comment by JeffHanna** [comment] 2019-09-24 01:10
Hello Dimitri,

Can you please provide more information? 
* Which version are you using, 1.0.1 stable release or the 1.1 beta release?
* Have you properly added the initialize_COM_server.ms script to your 3ds Max startup scripts folder?

I am unable to reproduce your error using either 1.0.1 or 1.1.

**Comment by JeffHanna** [comment] 2019-09-26 13:08
I'm unable to reproduce this issue and the submitter has not responded to a request for more information. I'm closing this issue.

**Closed by JeffHanna** 2019-09-26 13:08 UTC
